#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 3 ] || [ "$#" -gt 4 ]; then
  echo "Usage: $0 <template_dir> <env_file> <output_dir> [override_env_file]"
  exit 1
fi

TEMPLATE_DIR="$1"
ENV_FILE="$2"
OUTPUT_DIR="$3"
OVERRIDE_ENV_FILE="${4:-}"

test -d "$TEMPLATE_DIR" || { echo "Template directory not found: $TEMPLATE_DIR"; exit 1; }
test -f "$ENV_FILE" || { echo "Environment file not found: $ENV_FILE"; exit 1; }
if [ -n "$OVERRIDE_ENV_FILE" ]; then
  test -f "$OVERRIDE_ENV_FILE" || { echo "Override environment file not found: $OVERRIDE_ENV_FILE"; exit 1; }
fi

ENV_BASENAME="$(basename "$ENV_FILE")"
ENV_NAME="${ENV_BASENAME%-oncloud.env}"
ENV_PARENT_DIR="$(cd "$(dirname "$ENV_FILE")" && pwd)"
SYSTEM_ENV_FILE="$(cd "$ENV_PARENT_DIR/.." && pwd)/system/${ENV_NAME}-system.env"

set -a
if [ -f "$SYSTEM_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$SYSTEM_ENV_FILE"
fi
# shellcheck disable=SC1090
source "$ENV_FILE"
if [ -n "$OVERRIDE_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$OVERRIDE_ENV_FILE"
fi
set +a

required_vars=(
  CONTROL_PLANE_NAME
  PUBLIC_HOST_PRIMARY
  GET_TOKEN_SERVICE_NAME
  GET_TOKEN_SERVICE_HOST
  ISSUER_URL
  KAOTIM_SERVICE_HOST
  REDIS_PASSWORD
  STANDARD_CORE_API_USER_CUSTOM_ID
  STANDARD_GENERAL_SERVICES_USER_CUSTOM_ID
  VAULT_CONFIG_STORE_ID
  STANDARD_CORE_API_RATE_LIMIT_MINUTE
  STANDARD_CORE_API_RATE_LIMIT_HOUR
  STANDARD_GENERAL_SERVICES_RATE_LIMIT_MINUTE
  STANDARD_GENERAL_SERVICES_RATE_LIMIT_HOUR
)

for var_name in "${required_vars[@]}"; do
  test -n "${!var_name:-}" || { echo "Missing required variable in $ENV_FILE: $var_name"; exit 1; }
done

# Normalize current env model:
# - Dev/Uat can keep the original single-Redis variables.
# - Prod can define explicit PRIMARY_* and PREPROD_* variables.
PRIMARY_REDIS_PARTIAL_ID="${PRIMARY_REDIS_PARTIAL_ID:-${REDIS_PARTIAL_ID:-}}"
PRIMARY_REDIS_PARTIAL_NAME="${PRIMARY_REDIS_PARTIAL_NAME:-${REDIS_PARTIAL_NAME:-}}"
PRIMARY_REDIS_PARTIAL_TYPE="${PRIMARY_REDIS_PARTIAL_TYPE:-${REDIS_PARTIAL_TYPE:-redis-ce}}"
PRIMARY_REDIS_PARTIAL_HOST="${PRIMARY_REDIS_PARTIAL_HOST:-${REDIS_PARTIAL_HOST:-${REDIS_HOST:-}}}"
PRIMARY_REDIS_PARTIAL_PASSWORD="${PRIMARY_REDIS_PARTIAL_PASSWORD:-${REDIS_PARTIAL_PASSWORD:-}}"
PRIMARY_REDIS_PARTIAL_USERNAME="${PRIMARY_REDIS_PARTIAL_USERNAME:-null}"
PRIMARY_REDIS_PARTIAL_SENTINEL_MASTER="${PRIMARY_REDIS_PARTIAL_SENTINEL_MASTER:-${REDIS_PARTIAL_SENTINEL_MASTER:-null}}"
PRIMARY_REDIS_PARTIAL_SENTINEL_NODES="${PRIMARY_REDIS_PARTIAL_SENTINEL_NODES:-${REDIS_PARTIAL_SENTINEL_NODES:-null}}"
PRIMARY_REDIS_PARTIAL_SENTINEL_PASSWORD="${PRIMARY_REDIS_PARTIAL_SENTINEL_PASSWORD:-${REDIS_PARTIAL_SENTINEL_PASSWORD:-null}}"
PRIMARY_REDIS_PARTIAL_SENTINEL_ROLE="${PRIMARY_REDIS_PARTIAL_SENTINEL_ROLE:-${REDIS_PARTIAL_SENTINEL_ROLE:-null}}"
PRIMARY_REDIS_PARTIAL_SENTINEL_USERNAME="${PRIMARY_REDIS_PARTIAL_SENTINEL_USERNAME:-${REDIS_PARTIAL_SENTINEL_USERNAME:-null}}"

PRIMARY_REDIS_CACHE_PARTIAL_ID="${PRIMARY_REDIS_CACHE_PARTIAL_ID:-${REDIS_CACHE_PARTIAL_ID:-}}"
PRIMARY_REDIS_CACHE_PARTIAL_NAME="${PRIMARY_REDIS_CACHE_PARTIAL_NAME:-${REDIS_CACHE_PARTIAL_NAME:-}}"
PRIMARY_REDIS_CACHE_PARTIAL_TYPE="${PRIMARY_REDIS_CACHE_PARTIAL_TYPE:-redis-ee}"
PRIMARY_REDIS_CACHE_PARTIAL_HOST="${PRIMARY_REDIS_CACHE_PARTIAL_HOST:-${REDIS_CACHE_HOST:-}}"
PRIMARY_REDIS_CACHE_PARTIAL_PASSWORD="${PRIMARY_REDIS_CACHE_PARTIAL_PASSWORD:-${REDIS_CACHE_PASSWORD:-}}"
PRIMARY_REDIS_CACHE_PARTIAL_USERNAME="${PRIMARY_REDIS_CACHE_PARTIAL_USERNAME:-null}"
PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_MASTER="${PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_MASTER:-${REDIS_CACHE_SENTINEL_MASTER:-null}}"
PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_NODES="${PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_NODES:-${REDIS_CACHE_SENTINEL_NODES:-null}}"
PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD="${PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD:-${REDIS_CACHE_SENTINEL_PASSWORD:-null}}"
PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_ROLE="${PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_ROLE:-${REDIS_CACHE_SENTINEL_ROLE:-null}}"
PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME="${PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME:-${REDIS_CACHE_PARTIAL_SENTINEL_USERNAME:-null}}"

ACTIVE_REDIS_PARTIAL_ID="${ACTIVE_REDIS_PARTIAL_ID:-$PRIMARY_REDIS_PARTIAL_ID}"
ACTIVE_REDIS_PARTIAL_NAME="${ACTIVE_REDIS_PARTIAL_NAME:-$PRIMARY_REDIS_PARTIAL_NAME}"
ACTIVE_REDIS_CACHE_PARTIAL_ID="${ACTIVE_REDIS_CACHE_PARTIAL_ID:-$PRIMARY_REDIS_CACHE_PARTIAL_ID}"
ACTIVE_REDIS_CACHE_PARTIAL_NAME="${ACTIVE_REDIS_CACHE_PARTIAL_NAME:-$PRIMARY_REDIS_CACHE_PARTIAL_NAME}"

primary_redis_required=(
  PRIMARY_REDIS_PARTIAL_ID
  PRIMARY_REDIS_PARTIAL_NAME
  PRIMARY_REDIS_PARTIAL_TYPE
  PRIMARY_REDIS_PARTIAL_HOST
  PRIMARY_REDIS_PARTIAL_PASSWORD
  PRIMARY_REDIS_CACHE_PARTIAL_ID
  PRIMARY_REDIS_CACHE_PARTIAL_NAME
  PRIMARY_REDIS_CACHE_PARTIAL_TYPE
  PRIMARY_REDIS_CACHE_PARTIAL_HOST
  PRIMARY_REDIS_CACHE_PARTIAL_PASSWORD
  ACTIVE_REDIS_PARTIAL_ID
  ACTIVE_REDIS_PARTIAL_NAME
  ACTIVE_REDIS_CACHE_PARTIAL_ID
  ACTIVE_REDIS_CACHE_PARTIAL_NAME
)

for var_name in "${primary_redis_required[@]}"; do
  test -n "${!var_name:-}" || { echo "Missing normalized Redis variable in $ENV_FILE: $var_name"; exit 1; }
done

HAS_PREPROD_REDIS=false
if [ -n "${PREPROD_REDIS_PARTIAL_ID:-}" ] || [ -n "${PREPROD_REDIS_CACHE_PARTIAL_ID:-}" ]; then
  preprod_required=(
    PREPROD_REDIS_PARTIAL_ID
    PREPROD_REDIS_PARTIAL_NAME
    PREPROD_REDIS_PARTIAL_TYPE
    PREPROD_REDIS_PARTIAL_HOST
    PREPROD_REDIS_PARTIAL_PASSWORD
    PREPROD_REDIS_CACHE_PARTIAL_ID
    PREPROD_REDIS_CACHE_PARTIAL_NAME
    PREPROD_REDIS_CACHE_PARTIAL_TYPE
    PREPROD_REDIS_CACHE_PARTIAL_HOST
    PREPROD_REDIS_CACHE_PARTIAL_PASSWORD
  )
  for var_name in "${preprod_required[@]}"; do
    test -n "${!var_name:-}" || { echo "Missing preprod Redis variable in $ENV_FILE: $var_name"; exit 1; }
  done
  PREPROD_REDIS_PARTIAL_USERNAME="${PREPROD_REDIS_PARTIAL_USERNAME:-null}"
  PREPROD_REDIS_PARTIAL_SENTINEL_MASTER="${PREPROD_REDIS_PARTIAL_SENTINEL_MASTER:-null}"
  PREPROD_REDIS_PARTIAL_SENTINEL_NODES="${PREPROD_REDIS_PARTIAL_SENTINEL_NODES:-null}"
  PREPROD_REDIS_PARTIAL_SENTINEL_PASSWORD="${PREPROD_REDIS_PARTIAL_SENTINEL_PASSWORD:-null}"
  PREPROD_REDIS_PARTIAL_SENTINEL_ROLE="${PREPROD_REDIS_PARTIAL_SENTINEL_ROLE:-null}"
  PREPROD_REDIS_PARTIAL_SENTINEL_USERNAME="${PREPROD_REDIS_PARTIAL_SENTINEL_USERNAME:-null}"
  PREPROD_REDIS_CACHE_PARTIAL_USERNAME="${PREPROD_REDIS_CACHE_PARTIAL_USERNAME:-null}"
  PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_MASTER="${PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_MASTER:-null}"
  PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_NODES="${PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_NODES:-null}"
  PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD="${PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD:-null}"
  PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_ROLE="${PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_ROLE:-null}"
  PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME="${PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME:-null}"
  HAS_PREPROD_REDIS=true
fi

export \
  PRIMARY_REDIS_PARTIAL_ID \
  PRIMARY_REDIS_PARTIAL_NAME \
  PRIMARY_REDIS_PARTIAL_TYPE \
  PRIMARY_REDIS_PARTIAL_HOST \
  PRIMARY_REDIS_PARTIAL_PASSWORD \
  PRIMARY_REDIS_PARTIAL_USERNAME \
  PRIMARY_REDIS_PARTIAL_SENTINEL_MASTER \
  PRIMARY_REDIS_PARTIAL_SENTINEL_NODES \
  PRIMARY_REDIS_PARTIAL_SENTINEL_PASSWORD \
  PRIMARY_REDIS_PARTIAL_SENTINEL_ROLE \
  PRIMARY_REDIS_PARTIAL_SENTINEL_USERNAME \
  PRIMARY_REDIS_CACHE_PARTIAL_ID \
  PRIMARY_REDIS_CACHE_PARTIAL_NAME \
  PRIMARY_REDIS_CACHE_PARTIAL_TYPE \
  PRIMARY_REDIS_CACHE_PARTIAL_HOST \
  PRIMARY_REDIS_CACHE_PARTIAL_PASSWORD \
  PRIMARY_REDIS_CACHE_PARTIAL_USERNAME \
  PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_MASTER \
  PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_NODES \
  PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD \
  PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_ROLE \
  PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME \
  ACTIVE_REDIS_PARTIAL_ID \
  ACTIVE_REDIS_PARTIAL_NAME \
  ACTIVE_REDIS_CACHE_PARTIAL_ID \
  ACTIVE_REDIS_CACHE_PARTIAL_NAME

if [ "$HAS_PREPROD_REDIS" = true ]; then
  export \
    PREPROD_REDIS_PARTIAL_ID \
    PREPROD_REDIS_PARTIAL_NAME \
    PREPROD_REDIS_PARTIAL_TYPE \
    PREPROD_REDIS_PARTIAL_HOST \
    PREPROD_REDIS_PARTIAL_PASSWORD \
    PREPROD_REDIS_PARTIAL_USERNAME \
    PREPROD_REDIS_PARTIAL_SENTINEL_MASTER \
    PREPROD_REDIS_PARTIAL_SENTINEL_NODES \
    PREPROD_REDIS_PARTIAL_SENTINEL_PASSWORD \
    PREPROD_REDIS_PARTIAL_SENTINEL_ROLE \
    PREPROD_REDIS_PARTIAL_SENTINEL_USERNAME \
    PREPROD_REDIS_CACHE_PARTIAL_ID \
    PREPROD_REDIS_CACHE_PARTIAL_NAME \
    PREPROD_REDIS_CACHE_PARTIAL_TYPE \
    PREPROD_REDIS_CACHE_PARTIAL_HOST \
    PREPROD_REDIS_CACHE_PARTIAL_PASSWORD \
    PREPROD_REDIS_CACHE_PARTIAL_USERNAME \
    PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_MASTER \
    PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_NODES \
    PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD \
    PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_ROLE \
    PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME
fi

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
cp -R "$TEMPLATE_DIR"/. "$OUTPUT_DIR"/

select_partial_template() {
  local ce_template="$1"
  local ee_template="$2"
  local output_file="$3"
  local partial_type="$4"

  case "$partial_type" in
    redis-ce)
      mv "$ce_template" "$output_file"
      rm -f "$ee_template"
      ;;
    redis-ee)
      mv "$ee_template" "$output_file"
      rm -f "$ce_template"
      ;;
    *)
      echo "Unsupported Redis partial type for $output_file: $partial_type"
      exit 1
      ;;
  esac
}

select_partial_template \
  "$OUTPUT_DIR/partials/001-primary-redis-partial-ce.yaml" \
  "$OUTPUT_DIR/partials/002-primary-redis-partial-ee.yaml" \
  "$OUTPUT_DIR/partials/001-primary-redis-partial.yaml" \
  "$PRIMARY_REDIS_PARTIAL_TYPE"

select_partial_template \
  "$OUTPUT_DIR/partials/003-primary-redis-cache-partial-ce.yaml" \
  "$OUTPUT_DIR/partials/004-primary-redis-cache-partial-ee.yaml" \
  "$OUTPUT_DIR/partials/002-primary-redis-cache-partial.yaml" \
  "$PRIMARY_REDIS_CACHE_PARTIAL_TYPE"

if [ "$HAS_PREPROD_REDIS" = true ]; then
  select_partial_template \
    "$OUTPUT_DIR/partials/005-preprod-redis-partial-ce.yaml" \
    "$OUTPUT_DIR/partials/006-preprod-redis-partial-ee.yaml" \
    "$OUTPUT_DIR/partials/003-preprod-redis-partial.yaml" \
    "$PREPROD_REDIS_PARTIAL_TYPE"

  select_partial_template \
    "$OUTPUT_DIR/partials/007-preprod-redis-cache-partial-ce.yaml" \
    "$OUTPUT_DIR/partials/008-preprod-redis-cache-partial-ee.yaml" \
    "$OUTPUT_DIR/partials/004-preprod-redis-cache-partial.yaml" \
    "$PREPROD_REDIS_CACHE_PARTIAL_TYPE"
else
  rm -f \
    "$OUTPUT_DIR/partials/005-preprod-redis-partial-ce.yaml" \
    "$OUTPUT_DIR/partials/006-preprod-redis-partial-ee.yaml" \
    "$OUTPUT_DIR/partials/007-preprod-redis-cache-partial-ce.yaml" \
    "$OUTPUT_DIR/partials/008-preprod-redis-cache-partial-ee.yaml"
fi

if [ "$ENV_NAME" = "prod" ]; then
  rm -f "$OUTPUT_DIR/consumers/001-standard-core-api-user.yaml"
  mv "$OUTPUT_DIR/consumers/001-standard-core-api-user-prod.yaml" "$OUTPUT_DIR/consumers/001-standard-core-api-user.yaml"
  rm -f "$OUTPUT_DIR/consumers/002-standard-general-services-user.yaml"
  mv "$OUTPUT_DIR/consumers/002-standard-general-services-user-prod.yaml" "$OUTPUT_DIR/consumers/002-standard-general-services-user.yaml"
else
  rm -f "$OUTPUT_DIR/consumers/001-standard-core-api-user-prod.yaml"
  rm -f "$OUTPUT_DIR/consumers/002-standard-general-services-user-prod.yaml"
fi

find "$OUTPUT_DIR" -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.md" \) -print0 | while IFS= read -r -d '' file; do
  perl -0pe '
    my %repl = (
      "__CONTROL_PLANE_NAME__" => $ENV{"CONTROL_PLANE_NAME"},
      "__PUBLIC_HOST_PRIMARY__" => $ENV{"PUBLIC_HOST_PRIMARY"},
      "__GET_TOKEN_SERVICE_NAME__" => $ENV{"GET_TOKEN_SERVICE_NAME"},
      "__GET_TOKEN_SERVICE_HOST__" => $ENV{"GET_TOKEN_SERVICE_HOST"},
      "__ISSUER_URL__" => $ENV{"ISSUER_URL"},
      "__REDIS_PASSWORD__" => $ENV{"REDIS_PASSWORD"},
      "__PRIMARY_REDIS_PARTIAL_ID__" => $ENV{"PRIMARY_REDIS_PARTIAL_ID"},
      "__PRIMARY_REDIS_PARTIAL_NAME__" => $ENV{"PRIMARY_REDIS_PARTIAL_NAME"},
      "__PRIMARY_REDIS_PARTIAL_HOST__" => $ENV{"PRIMARY_REDIS_PARTIAL_HOST"},
      "__PRIMARY_REDIS_PARTIAL_PASSWORD__" => $ENV{"PRIMARY_REDIS_PARTIAL_PASSWORD"},
      "__PRIMARY_REDIS_PARTIAL_USERNAME__" => $ENV{"PRIMARY_REDIS_PARTIAL_USERNAME"},
      "__PRIMARY_REDIS_PARTIAL_SENTINEL_MASTER__" => $ENV{"PRIMARY_REDIS_PARTIAL_SENTINEL_MASTER"},
      "__PRIMARY_REDIS_PARTIAL_SENTINEL_NODES__" => $ENV{"PRIMARY_REDIS_PARTIAL_SENTINEL_NODES"},
      "__PRIMARY_REDIS_PARTIAL_SENTINEL_PASSWORD__" => $ENV{"PRIMARY_REDIS_PARTIAL_SENTINEL_PASSWORD"},
      "__PRIMARY_REDIS_PARTIAL_SENTINEL_ROLE__" => $ENV{"PRIMARY_REDIS_PARTIAL_SENTINEL_ROLE"},
      "__PRIMARY_REDIS_PARTIAL_SENTINEL_USERNAME__" => $ENV{"PRIMARY_REDIS_PARTIAL_SENTINEL_USERNAME"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_ID__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_ID"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_NAME__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_NAME"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_HOST__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_HOST"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_PASSWORD__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_PASSWORD"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_USERNAME__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_USERNAME"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_MASTER__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_MASTER"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_NODES__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_NODES"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_ROLE__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_ROLE"},
      "__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME__" => $ENV{"PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME"},
      "__PREPROD_REDIS_PARTIAL_ID__" => $ENV{"PREPROD_REDIS_PARTIAL_ID"},
      "__PREPROD_REDIS_PARTIAL_NAME__" => $ENV{"PREPROD_REDIS_PARTIAL_NAME"},
      "__PREPROD_REDIS_PARTIAL_HOST__" => $ENV{"PREPROD_REDIS_PARTIAL_HOST"},
      "__PREPROD_REDIS_PARTIAL_PASSWORD__" => $ENV{"PREPROD_REDIS_PARTIAL_PASSWORD"},
      "__PREPROD_REDIS_PARTIAL_USERNAME__" => $ENV{"PREPROD_REDIS_PARTIAL_USERNAME"},
      "__PREPROD_REDIS_PARTIAL_SENTINEL_MASTER__" => $ENV{"PREPROD_REDIS_PARTIAL_SENTINEL_MASTER"},
      "__PREPROD_REDIS_PARTIAL_SENTINEL_NODES__" => $ENV{"PREPROD_REDIS_PARTIAL_SENTINEL_NODES"},
      "__PREPROD_REDIS_PARTIAL_SENTINEL_PASSWORD__" => $ENV{"PREPROD_REDIS_PARTIAL_SENTINEL_PASSWORD"},
      "__PREPROD_REDIS_PARTIAL_SENTINEL_ROLE__" => $ENV{"PREPROD_REDIS_PARTIAL_SENTINEL_ROLE"},
      "__PREPROD_REDIS_PARTIAL_SENTINEL_USERNAME__" => $ENV{"PREPROD_REDIS_PARTIAL_SENTINEL_USERNAME"},
      "__PREPROD_REDIS_CACHE_PARTIAL_ID__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_ID"},
      "__PREPROD_REDIS_CACHE_PARTIAL_NAME__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_NAME"},
      "__PREPROD_REDIS_CACHE_PARTIAL_HOST__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_HOST"},
      "__PREPROD_REDIS_CACHE_PARTIAL_PASSWORD__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_PASSWORD"},
      "__PREPROD_REDIS_CACHE_PARTIAL_USERNAME__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_USERNAME"},
      "__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_MASTER__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_MASTER"},
      "__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_NODES__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_NODES"},
      "__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD"},
      "__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_ROLE__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_ROLE"},
      "__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME__" => $ENV{"PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME"},
      "__ACTIVE_REDIS_PARTIAL_ID__" => $ENV{"ACTIVE_REDIS_PARTIAL_ID"},
      "__ACTIVE_REDIS_PARTIAL_NAME__" => $ENV{"ACTIVE_REDIS_PARTIAL_NAME"},
      "__ACTIVE_REDIS_CACHE_PARTIAL_ID__" => $ENV{"ACTIVE_REDIS_CACHE_PARTIAL_ID"},
      "__ACTIVE_REDIS_CACHE_PARTIAL_NAME__" => $ENV{"ACTIVE_REDIS_CACHE_PARTIAL_NAME"},
      "__KAOTIM_SERVICE_HOST__" => $ENV{"KAOTIM_SERVICE_HOST"},
      "__STANDARD_CORE_API_USER_CUSTOM_ID__" => $ENV{"STANDARD_CORE_API_USER_CUSTOM_ID"},
      "__STANDARD_GENERAL_SERVICES_USER_CUSTOM_ID__" => $ENV{"STANDARD_GENERAL_SERVICES_USER_CUSTOM_ID"},
      "__VAULT_CONFIG_STORE_ID__" => $ENV{"VAULT_CONFIG_STORE_ID"},
      "__STANDARD_CORE_API_RATE_LIMIT_MINUTE__" => $ENV{"STANDARD_CORE_API_RATE_LIMIT_MINUTE"},
      "__STANDARD_CORE_API_RATE_LIMIT_HOUR__" => $ENV{"STANDARD_CORE_API_RATE_LIMIT_HOUR"},
      "__STANDARD_GENERAL_SERVICES_RATE_LIMIT_MINUTE__" => $ENV{"STANDARD_GENERAL_SERVICES_RATE_LIMIT_MINUTE"},
      "__STANDARD_GENERAL_SERVICES_RATE_LIMIT_HOUR__" => $ENV{"STANDARD_GENERAL_SERVICES_RATE_LIMIT_HOUR"},
      "__OPTIONAL_PUBLIC_HOST_SECONDARY__" => length($ENV{"PUBLIC_HOST_SECONDARY"} // q{}) ? "  - " . $ENV{"PUBLIC_HOST_SECONDARY"} : q{},
    );
    s/(__CONTROL_PLANE_NAME__|__PUBLIC_HOST_PRIMARY__|__GET_TOKEN_SERVICE_NAME__|__GET_TOKEN_SERVICE_HOST__|__ISSUER_URL__|__REDIS_PASSWORD__|__PRIMARY_REDIS_PARTIAL_ID__|__PRIMARY_REDIS_PARTIAL_NAME__|__PRIMARY_REDIS_PARTIAL_HOST__|__PRIMARY_REDIS_PARTIAL_PASSWORD__|__PRIMARY_REDIS_PARTIAL_USERNAME__|__PRIMARY_REDIS_PARTIAL_SENTINEL_MASTER__|__PRIMARY_REDIS_PARTIAL_SENTINEL_NODES__|__PRIMARY_REDIS_PARTIAL_SENTINEL_PASSWORD__|__PRIMARY_REDIS_PARTIAL_SENTINEL_ROLE__|__PRIMARY_REDIS_PARTIAL_SENTINEL_USERNAME__|__PRIMARY_REDIS_CACHE_PARTIAL_ID__|__PRIMARY_REDIS_CACHE_PARTIAL_NAME__|__PRIMARY_REDIS_CACHE_PARTIAL_HOST__|__PRIMARY_REDIS_CACHE_PARTIAL_PASSWORD__|__PRIMARY_REDIS_CACHE_PARTIAL_USERNAME__|__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_MASTER__|__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_NODES__|__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD__|__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_ROLE__|__PRIMARY_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME__|__PREPROD_REDIS_PARTIAL_ID__|__PREPROD_REDIS_PARTIAL_NAME__|__PREPROD_REDIS_PARTIAL_HOST__|__PREPROD_REDIS_PARTIAL_PASSWORD__|__PREPROD_REDIS_PARTIAL_USERNAME__|__PREPROD_REDIS_PARTIAL_SENTINEL_MASTER__|__PREPROD_REDIS_PARTIAL_SENTINEL_NODES__|__PREPROD_REDIS_PARTIAL_SENTINEL_PASSWORD__|__PREPROD_REDIS_PARTIAL_SENTINEL_ROLE__|__PREPROD_REDIS_PARTIAL_SENTINEL_USERNAME__|__PREPROD_REDIS_CACHE_PARTIAL_ID__|__PREPROD_REDIS_CACHE_PARTIAL_NAME__|__PREPROD_REDIS_CACHE_PARTIAL_HOST__|__PREPROD_REDIS_CACHE_PARTIAL_PASSWORD__|__PREPROD_REDIS_CACHE_PARTIAL_USERNAME__|__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_MASTER__|__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_NODES__|__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_PASSWORD__|__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_ROLE__|__PREPROD_REDIS_CACHE_PARTIAL_SENTINEL_USERNAME__|__ACTIVE_REDIS_PARTIAL_ID__|__ACTIVE_REDIS_PARTIAL_NAME__|__ACTIVE_REDIS_CACHE_PARTIAL_ID__|__ACTIVE_REDIS_CACHE_PARTIAL_NAME__|__KAOTIM_SERVICE_HOST__|__STANDARD_CORE_API_USER_CUSTOM_ID__|__STANDARD_GENERAL_SERVICES_USER_CUSTOM_ID__|__VAULT_CONFIG_STORE_ID__|__STANDARD_CORE_API_RATE_LIMIT_MINUTE__|__STANDARD_CORE_API_RATE_LIMIT_HOUR__|__STANDARD_GENERAL_SERVICES_RATE_LIMIT_MINUTE__|__STANDARD_GENERAL_SERVICES_RATE_LIMIT_HOUR__|__OPTIONAL_PUBLIC_HOST_SECONDARY__)/$repl{$1}/ge;
  ' "$file" > "${file}.tmp"
  mv "${file}.tmp" "$file"
done

if grep -R -n -E '__[A-Z0-9_]+__' "$OUTPUT_DIR" >/dev/null; then
  echo "Unresolved template tokens found in rendered output:"
  grep -R -n -E '__[A-Z0-9_]+__' "$OUTPUT_DIR"
  exit 1
fi

PYTHON_BIN=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1; then
    PYTHON_BIN="$candidate"
    break
  fi
done

test -n "$PYTHON_BIN" || { echo "python3 or python is required for rendered partial reference validation"; exit 1; }

"$PYTHON_BIN" - "$OUTPUT_DIR" <<'PY'
import os
import re
import sys

root = sys.argv[1]

def clean(value: str) -> str:
    return value.strip().strip('"').strip("'")

partial_defs = set()
partial_def_files = []
partial_refs = []

for dirpath, _, filenames in os.walk(root):
    for filename in filenames:
        if not filename.endswith((".yaml", ".yml")):
            continue
        path = os.path.join(dirpath, filename)
        rel = os.path.relpath(path, root).replace("\\", "/")
        text = open(path, encoding="utf-8").read()

        if rel.startswith("partials/"):
          partial_def_files.append(rel)
          id_match = re.search(r'(?m)^[ \t]*id:\s*(.+?)\s*$', text)
          name_match = re.search(r'(?m)^[ \t]*name:\s*(.+?)\s*$', text)
          if not id_match or not name_match:
              print(f"Unable to resolve partial id/name from rendered partial file: {rel}")
              sys.exit(1)
          partial_defs.add((clean(id_match.group(1)), clean(name_match.group(1))))
          continue

        lines = text.splitlines()
        in_partials = False
        current_ref = None
        partial_indent = None

        for line_no, line in enumerate(lines, start=1):
            stripped = line.strip()
            indent = len(line) - len(line.lstrip())

            if stripped == "partials:":
                in_partials = True
                partial_indent = indent
                current_ref = None
                continue

            if not in_partials:
                continue

            if stripped and indent < partial_indent and stripped != "partials:":
                in_partials = False
                current_ref = None
                partial_indent = None
                continue

            id_match = re.match(r'^\s*-\s+id:\s*(.+?)\s*$', line)
            if id_match:
                current_ref = {"id": clean(id_match.group(1)), "line": line_no}
                continue

            if current_ref is None:
                continue

            name_match = re.match(r'^\s*name:\s*(.+?)\s*$', line)
            if name_match:
                current_ref["name"] = clean(name_match.group(1))
                continue

            path_match = re.match(r'^\s*path:\s*(.+?)\s*$', line)
            if path_match:
                current_ref["path"] = clean(path_match.group(1))
                partial_refs.append((current_ref["id"], current_ref.get("name", ""), rel, current_ref["line"]))
                current_ref = None

if not partial_def_files:
    print("No rendered partial definition files were found.")
    sys.exit(1)

missing = []
for ref_id, ref_name, rel, line_no in partial_refs:
    if (ref_id, ref_name) not in partial_defs:
        missing.append((ref_id, ref_name, rel, line_no))

if missing:
    print("Rendered plugin partial references do not match rendered partial entities:")
    for ref_id, ref_name, rel, line_no in missing:
        print(f"  {rel}:{line_no} -> id={ref_id}, name={ref_name}")
    sys.exit(1)

print(f"Validated rendered partial references: {len(partial_defs)} partials, {len(partial_refs)} plugin references.")
PY

echo "Rendered Kong state to: $OUTPUT_DIR"
